server:
  port: 5003

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:7050/eureka"
  instances:
    leaseRenewalIntervalInSeconds: 5
spring:
  jpa:
    show-sql: 'true'
  h2:
    console:
      enabled: 'true'
      path: '/h2-console'

#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: true
#        sql: 'DEBUG'
#