server:
  port: 5002

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:7050/eureka"
  instances:
    leaseRenewalIntervalInSeconds: 10
spring:
  data:
    mongodb:
      database: 'masterdb'
  jpa:
    show-sql: 'true'
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected=: false
rabbit:
  product:
    topic: "product-queue"
    topicExchange: "product-update"
    routingKey: "product.update.#"


#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: true
#        sql: 'DEBUG'
#