server:
  port: 5001

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:7050/eureka"
  instances:
    leaseRenewalIntervalInSeconds: 10
spring:
  data:
    mongodb:
      database: 'masterdb'
  jpa:
    show-sql: 'true'

#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: true
#        sql: 'DEBUG'
#